# Generated by Django 2.2.6 on 2019-11-04 06:01

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('vendedores', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Listado',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('direccion', models.CharField(max_length=200)),
                ('departamento', models.CharField(max_length=100)),
                ('municipio', models.CharField(max_length=100)),
                ('descripcion', models.TextField(blank=True)),
                ('precio', models.IntegerField()),
                ('dormitorios', models.IntegerField()),
                ('banios', models.DecimalField(decimal_places=1, max_digits=2)),
                ('garage', models.IntegerField(default=0)),
                ('mts', models.IntegerField()),
                ('foto', models.ImageField(upload_to='photos/%Y/%m/%d/')),
                ('foto1', models.ImageField(blank=True, upload_to='photos/%Y/%m/%d/')),
                ('foto2', models.ImageField(blank=True, upload_to='photos/%Y/%m/%d/')),
                ('foto3', models.ImageField(blank=True, upload_to='photos/%Y/%m/%d/')),
                ('publicado', models.BooleanField(default=True)),
                ('fecha', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('vendedor', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='vendedores.Vendedor')),
            ],
        ),
    ]
