# Generated by Django 2.2.6 on 2019-11-04 06:01

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Vendedor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('foto', models.ImageField(upload_to='fotos/%Y/%m/%d/')),
                ('descripcion', models.TextField(blank=True)),
                ('telefono', models.CharField(max_length=20)),
                ('email', models.CharField(max_length=50)),
                ('is_mvp', models.BooleanField(default=False)),
                ('fecha_cont', models.DateTimeField(blank=True, default=datetime.datetime.now)),
            ],
        ),
    ]
